### ISSUE TITLE
Agent crashes fetching EPL Models

### ISSUE THREAD

**Issue by switschel** [mbay-SAG/cumulocity-thinedge-example#1]
2020-11-20 17:55:00,227 - deviceAgent - ERROR - The following error occured:
Traceback (most recent call last):
  File "run.py", line 97, in <module>
    start()
  File "run.py", line 55, in start
    streamingAnalytics.modelSync.models()
  File "/home/pi/cumulocity-thinedge-example/Agents/streamingAnalytics/modelSync.py", line 18, in models
    models = API.epl.getModels()
  File "/home/pi/cumulocity-thinedge-example/Agents/API/epl.py", line 34, in getModels
    raise Exception
Exception

Suggestions: This could should be handled by modelSync.py and should not lead to crashing the whole Agent.

**Comment by mbay-SAG** [comment]
Can confirm, will commit fix.
